"""
Infrastructure: Telegram account-linking token signing.

Uses itsdangerous.URLSafeTimedSerializer to create and verify signed,
time-limited linking tokens — the same library and pattern as
presentation/api/csrf.py's OAuth2 state tokens, but with a distinct `salt`
("telegram-link" instead of "oauth2-state") so a token generated for one
purpose can't be replayed as another. See design.md decision 4.
"""

from uuid import UUID

from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer
from itsdangerous.exc import BadData

from mobility_manager.config import get_jwt_secret

_LINK_TOKEN_MAX_AGE = 600  # 10 minutes


def _get_serializer() -> URLSafeTimedSerializer:
    return URLSafeTimedSerializer(get_jwt_secret(), salt="telegram-link")


def generate_link_token(user_id: UUID) -> str:
    """
    Generate a signed, time-limited Telegram linking token for `user_id`.

    Expires after 10 minutes.
    """
    payload = {"user_id": str(user_id)}
    return _get_serializer().dumps(payload)


def verify_link_token(token: str) -> UUID:
    """
    Verify a Telegram linking token generated by generate_link_token.

    Returns:
        The user_id encoded in the token.

    Raises:
        ValueError: If the token is tampered, expired, or otherwise invalid.
    """
    try:
        payload = _get_serializer().loads(token, max_age=_LINK_TOKEN_MAX_AGE)
    except SignatureExpired as exc:
        raise ValueError("Telegram link token has expired") from exc
    except (BadSignature, BadData) as exc:
        raise ValueError("Telegram link token is invalid") from exc

    try:
        return UUID(payload["user_id"])
    except (KeyError, ValueError, TypeError) as exc:
        raise ValueError("Telegram link token payload is invalid") from exc
