"""
Presentation: OAuth2 state parameter signing.

Uses itsdangerous.URLSafeTimedSerializer to create and verify signed, time-limited
state tokens for the OAuth2 CSRF protection flow. This replaces a state cookie
(which would fail to transmit under SameSite=Strict on the callback redirect).
"""

import secrets

from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer
from itsdangerous.exc import BadData

from mobility_manager.config import get_jwt_secret

_STATE_MAX_AGE = 300  # 5 minutes


def _get_serializer() -> URLSafeTimedSerializer:
    return URLSafeTimedSerializer(get_jwt_secret(), salt="oauth2-state")


def generate_signed_state() -> str:
    """
    Generate a signed, time-limited OAuth2 state token.

    The token contains a random nonce and is signed with JWT_SECRET.
    Expires after 5 minutes.
    """
    payload = {"nonce": secrets.token_hex(16)}
    return _get_serializer().dumps(payload)


def verify_signed_state(state: str) -> None:
    """
    Verify an OAuth2 state token generated by generate_signed_state.

    Raises:
        ValueError: If the token is tampered, expired, or otherwise invalid.
    """
    try:
        _get_serializer().loads(state, max_age=_STATE_MAX_AGE)
    except SignatureExpired as exc:
        raise ValueError("OAuth2 state token has expired") from exc
    except (BadSignature, BadData) as exc:
        raise ValueError("OAuth2 state token is invalid") from exc
